- name: PROJECT -->Create path project 
  become: yes
  file:
   path: "/usr/local/rails_app"
   state: directory
   owner: "{{ deploy_user }}"
   group: "{{ deploy_user }}"

- name: PROJECT -->  Create project {{ project_name }}
  become_user: "{{ deploy_user }}"
  become: yes
  git: 
    repo: https://github.com/oMaiThanhLong/blog.git
    dest: "{{ path_project }}"
# on nginx 
- name: NGINX --> Disable the default site
  become: yes
  file:
    path: "{{nginx_conf_dir}}/sites-enabled/default"
    state: absent

- name: NGINX --> Remove the default configuration
  become: yes
  file:
    path: "{{nginx_conf_dir}}/conf.d/default.conf"
    state: absent

- name: NGINX --> Copy the nginx configuration file
  become: yes
  template:
    src: config.conf.j2
    dest: "{{nginx_conf_dir}}/sites-available/webserver.conf"

- name: NGINX --> Create symbolic link 
  become: yes
  file:
    src: "{{nginx_conf_dir}}/sites-available/webserver.conf"
    dest: "{{ nginx_conf_dir }}/sites-enabled/webserver"
    state: link
- name: Restart  nginx
  become: yes
  service:
    name: nginx
    state: restarted
  register: status_nginx_project 
- debug:
    var: status_nginx_project.status

- name: Restart puma
  become: yes
  service:
    name: puma
    state: restarted
  register: status_puma
- debug:
    var: status_puma.status

- name : PROJECT --> Run project {{ project_name }}
  become_user: "{{ deploy_user }}"
  become: yes
  shell: | 
    bash -lc "bundle install"
    bash -lc  "bundle exec puma -e production -b unix:{{ server_unix }} -d"
  args:
    chdir:  "{{  path_project }}"
