- name: PUMA --> Install puma
  become_user: "{{ deploy_user }}"
  become: yes
  gem: 
    name: puma
    version: "{{ puma_version }}"
    executable: "{{ rbenv_install_dir }}/shims/gem"
    user_install: False

- name: PUMA --> Create puma systemd service
  become: yes
  template: 
    src: puma.service 
    dest: /etc/systemd/system
    owner: "{{puma_user}}"
    group: "{{puma_group}}"
    mode: 0754
