- name: PROJECT -->  Create project {{ project_name }}
  become_user: "{{ deploy_user }}"
  become: yes
  become_method: sudo
  shell: bash -lc " rails new {{ project_name }} "
  args:
    chdir: /home/{{ deploy_user }}/
    creates: /home/{{ deploy_user }}/{{ project_name }}

- name: PROJECT -->  Create directory sockets
  become_user: "{{ deploy_user }}"
  become: yes
  file:
   path: "{{path_project}}/tmp/sockets"
   state: directory
# on project :
- name: PROJECT --> include file index.html to {{project_name}}/public
  become_user: "{{ deploy_user}}"
  become: yes
  template:
    src: index.html
    dest: "/home/{{ deploy_user }}/{{ project_name}}/public/index.html"
  
# on project : change evironment of puma.rb to production
- name: PUMA --> change evironment of puma.rb from development to production
  become_user: "{{ deploy_user}}"
  become: yes
  replace:
    path: /home/{{ deploy_user }}/{{ project_name}}/config/puma.rb
    regexp: 'development'
    replace: 'production'
# on nginx 
- name: NGINX --> Disable the default site
  become: yes
  file:
    path: "{{nginx_conf_dir}}/sites-enabled/default"
    state: absent

- name: NGINX --> Remove the default configuration
  become: yes
  file:
    path: "{{nginx_conf_dir}}/conf.d/default.conf"
    state: absent

- name: NGINX --> Copy the nginx configuration file
  become: yes
  template:
    src: nginx.conf.j2
    dest: "{{ app_nginx_conf_dir }}/nginx.conf"

- name: NGINX --> Create symbolic link 
  become: yes
  file:
    src: "{{ app_nginx_conf_dir }}/nginx.conf"
    dest: "{{ nginx_conf_dir }}/sites-enabled/nginx"
    state: link
- name: Restart  nginx
  service:
    name: nginx
    state: restarted
  become: yes

- name : PROJECT --> Run project {{ project_name }}
  become_user: "{{ deploy_user }}"
  become: yes
  shell: bash -lc  "bundle exec puma -e production -b unix:{{ server_unix }} -d"
  args:
    chdir:  /home/{{ deploy_user }}/{{ project_name }}
